#!/bin/sh

#为执行shell路径生成tags
#nowpath=`pwd`
#ctags -R --c++-kinds=+px --fields=+iaS --extra=+q .
#echo 'generate ctags from "'$nowpath'" ok'

#为主工作目录设置ctags
workpath='/home/ecs-user/workspace/'
cd $workpath
ctags -R --c++-kinds=+px --fields=+iaS --extra=+q .
echo 'generate ctags from "'$workpath'" ok'


#获取shell所在路径
mypath=`dirname $0`
echo 'shell script is '$mypath


